background {
    monitor = eDP-1
    path = /home/ganchy/Pictures/Wallpapers/wallhaven-wqm2e6.jpg
    color = rgba(17,17,18,1.0)
    blur_passes = 5
}

input-field {
    monitor = eDP-1
    size = 20%, 5%
    outline_thickness = 3

    inner_color = rgba(0, 0, 0, 0.0)

    # Normal state: bright primary + secondary accent.
    outer_color = rgba(211,198,152,1.0) rgba(218,204,170,1.0) 45deg

    # Successful authentication.
    check_color = rgba(200,179,127,1.0) rgba(211,198,152,1.0) 120deg

    # Authentication failure.
    fail_color = rgba(177,194,112,1.0) rgba(218,204,170,1.0) 40deg

    font_color = rgba(195,195,195,1.0)

    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}
